# Generated by Django 2.2.1 on 2019-05-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0002_auto_20190516_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='types',
            field=models.BooleanField(choices=[(True, 'Worker'), (False, 'Employer')], verbose_name='Sign up as'),
        ),
    ]
